In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('D:\\BlueStock FineTech\\data\\raw\\04_monthly_sip_inflows.csv')

In [ ]:
df

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
12,2023-01,13856,6.13,9.10,5.82,20.31
13,2023-02,13687,6.19,8.20,5.88,19.66
14,2023-03,14276,6.32,10.00,6.01,15.80
15,2023-04,14749,6.41,9.25,6.15,24.33
16,2023-05,14749,6.50,8.70,6.22,20.05
17,2023-06,14734,6.55,7.90,6.30,20.02
18,2023-07,15245,6.65,9.80,6.45,25.58
19,2023-08,15814,6.73,9.10,6.58,24.58
20,2023-09,16042,6.82,10.20,6.72,23.63
21,2023-10,16928,6.91,9.50,6.90,29.82
22,2023-11,17073,7.00,8.80,7.05,28.31
23,2023-12,17610,7.10,8.40,7.18,29.74
24,2024-01,18838,7.20,9.60,7.35,35.96
25,2024-02,19187,7.30,8.50,7.52,40.18
26,2024-03,20371,7.40,9.00,7.71,42.69
27,2024-04,20371,7.60,9.40,7.90,38.12
28,2024-05,21262,7.78,8.90,8.15,44.16
29,2024-06,21262,7.90,8.20,8.35,44.31
30,2024-07,23332,8.00,10.00,8.56,53.05
31,2024-08,23547,8.11,9.80,8.78,48.90
32,2024-09,24509,8.22,9.20,8.98,52.78
33,2024-10,25323,8.30,9.55,9.22,49.59
34,2024-11,25320,8.40,9.10,9.45,48.30
35,2024-12,26459,8.50,9.30,9.70,50.25
36,2025-01,26400,8.22,9.10,13.00,40.14
37,2025-02,25999,8.30,8.60,13.18,35.50
38,2025-03,25926,8.11,7.80,13.35,27.27
39,2025-04,26632,8.38,46.00,13.55,30.73
40,2025-05,26688,8.50,9.20,13.72,25.52
41,2025-06,27274,8.62,9.50,13.88,28.28
42,2025-07,28464,8.75,10.20,14.05,22.00
43,2025-08,28265,8.85,9.80,15.18,20.04
44,2025-09,29361,9.00,10.50,15.38,19.80
45,2025-10,29529,9.10,9.45,15.55,16.61
46,2025-11,30200,9.20,9.10,15.72,19.27
47,2025-12,31002,9.35,9.80,15.90,17.17

In [8]:
df.head(2)

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.1,4.80,NaN
1,2022-02,11438,4.93,8.2,4.85,NaN

In [16]:
df.isnull().sum()/df.shape[0]
#print(df.duplicated().sum())

month                        0.0
sip_inflow_crore             0.0
active_sip_accounts_crore    0.0
new_sip_accounts_lakh        0.0
sip_aum_lakh_crore           0.0
yoy_growth_pct               0.0
dtype: float64

In [17]:
df.shape[0]

36

In [15]:
df.dropna(inplace=True)

# Explore Fund Master

In [21]:
fund_master = pd.read_csv(
    "D:\\BlueStock FineTech\\data\\raw\\01_fund_master.csv"
)

In [26]:
fund_master.head(2)

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01

In [29]:
print(
    fund_master['fund_house'].nunique()
)

print(
    fund_master['category'].unique()
)

print(
    fund_master['sub_category'].unique()
)

print(
    fund_master['risk_category'].unique()
)

10
['Equity' 'Debt']
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [25]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [30]:
fund_master = pd.read_csv(
    "D:\\BlueStock FineTech\\data\\raw\\01_fund_master.csv"
)

nav_history = pd.read_csv(
    "D:\\BlueStock FineTech\\data\\raw\\02_nav_history.csv"
)

In [31]:
master_codes = set(
    fund_master['amfi_code']
)

nav_codes = set(
    nav_history['amfi_code']
)

In [32]:
missing_codes = (
    master_codes - nav_codes
)

print(
    "Missing Codes:",
    len(missing_codes)
)

Missing Codes: 0

In [33]:
duplicate_amfi = fund_master['amfi_code'].duplicated().sum()

print("Duplicate AMFI Codes:", duplicate_amfi)

Duplicate AMFI Codes: 0

In [34]:
print(fund_master['category'].isnull().sum())
print(fund_master['sub_category'].isnull().sum())
print(fund_master['risk_category'].isnull().sum())

0
0
0

In [35]:
missing_nav = nav_history['nav'].isnull().sum()

print("Missing NAV Values:", missing_nav)

Missing NAV Values: 0

In [36]:
master_codes = set(fund_master['amfi_code'])
nav_codes = set(nav_history['amfi_code'])

total_master = len(master_codes)

In [37]:
missing_codes = master_codes - nav_codes

print("Missing Codes:", len(missing_codes))

Missing Codes: 0

In [38]:
found_codes = len(master_codes & nav_codes)

percentage_found = (
    found_codes / total_master
) * 100

print(
    f"AMFI Codes Found: {percentage_found:.2f}%"
)

AMFI Codes Found: 100.00%

In [ ]:
print(
    fund_master['fund_house'].nunique()
)

print(
    fund_master['category'].unique()
)

print(
    fund_master['sub_category'].unique()
)

print(
    fund_master['risk_category'].unique()
)

10
['Equity' 'Debt']
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

# Generate Summary Automatically

In [39]:
duplicate_amfi = fund_master['amfi_code'].duplicated().sum()

missing_nav = nav_history['nav'].isnull().sum()

duplicate_rows = nav_history.duplicated(
    subset=['amfi_code','date']
).sum()

master_codes = set(fund_master['amfi_code'])
nav_codes = set(nav_history['amfi_code'])

missing_codes = master_codes - nav_codes

found_pct = (
    len(master_codes & nav_codes)
    / len(master_codes)
) * 100

print("\nDATA QUALITY SUMMARY")

print("\n1. fund_master.csv")
print(f"   - Duplicate AMFI Codes: {duplicate_amfi}")

if (
    fund_master['category'].isnull().sum() == 0
    and fund_master['sub_category'].isnull().sum() == 0
    and fund_master['risk_category'].isnull().sum() == 0
):
    print("   - Category information complete")

print("\n2. nav_history.csv")
print(f"   - Missing NAV values: {missing_nav}")
print(f"   - Duplicate rows: {duplicate_rows}")

print("\n3. AMFI Validation")
print(f"   - {found_pct:.2f}% AMFI codes found")
print(f"   - {len(missing_codes)} codes missing NAV history")

DATA QUALITY SUMMARY

1. fund_master.csv
   - Duplicate AMFI Codes: 0
   - Category information complete

2. nav_history.csv
   - Missing NAV values: 0
   - Duplicate rows: 0

3. AMFI Validation
   - 100.00% AMFI codes found
   - 0 codes missing NAV history